### ISSUE TITLE
TorXakis compiler treats constant functions and constdefs in a different way, is that intentional?

### ISSUE THREAD

**Issue by dnadales** [TorXakis/TorXakis#722] opened 2018-06-05 09:19 UTC
Consider the following model:

```text
CONSTDEF
    xx :: Int ::= 3
ENDDEF

FUNCDEF yy() :: Int ::=
    3
ENDDEF

FUNCDEF gg() :: Int ::=
    xx * 10
ENDDEF

FUNCDEF hh() :: Int ::=
    yy * 10
ENDDEF
```

The `ValExpr` for `hh` will be:

```haskell
Vsum
    [ ( SumTerm
        { summand =
              ValExpr
              { view =
                    Vfunc
                        (FuncId
                         { name = "yy"
                         , unid = 0
                         , funcargs = []
                         , funcsort = SortId {name = "Int", unid = 0}
                         })
                        []
              }
        }
      , 10)
    ]
```

Whereas the `ValExpr` for `gg` will be:

```haskell
 Vconst (Cint {cInt = 30})}
```

The new compiler produces the latter expression in both cases, but I don't know if this is desired.

**Comment by pjljvandelaar** [comment] 2018-06-06 06:44
Producing 30 in both cases is desired in my humble opinion.

The result is 30 in both cases. Yet just 30 is faster with respect to performance so is desired.

**Comment by pjljvandelaar** [comment] 2018-06-06 07:01
Note the difference is caused by recursive functions. The current compiler doesn't look inside since it might be recursive.

**Comment by dnadales** [comment] 2018-06-06 07:37
> Producing 30 in both cases is desired in my humble opinion.

Ok, I guess that's good news for me since that's what the new compiler produces.

> Note the difference is caused by recursive functions. The current compiler doesn't look inside since it might be recursive.

Indeed. The gist of how the new compiler build functions is given below:

```haskell
    let
        fsig = Signature (funcargs fid) (funcsort fid)
        handler' = cstrFunc (Map.empty :: Map FuncId (FuncDef VarId)) fid
        -- In case of a recursive function, we need to make the information of
        -- the current function available to @expDeclToValExpr@.
        locToSigHdlrMap =
            Map.insert (getLoc f) (fsig, handler') (innerSigHandlerMap mm)
    -- Calculate the ValExpr of the function body:
    vExp <- expDeclToValExpr (locToSigHdlrMap <.+> mm) (funcsort fid) (funcBody f)
    let fdef = FuncDef pIds vExp
        -- We recalculate the handler to simplify constant expressions.
        fhandler =
            case funcargs fid of
                [] -> const vExp
                _  -> handler'
```

So in case of a recursive functions with no arguments, the body of the function will be returned (`const vExp`), but no further simplifications will be made. So as far as I can see we're safe regarding recursive functions. For instance, the new compiler won't hang in the following `FUNCDEF`:

```text
FUNCDEF f() :: Int ::=
    f()
ENDDEF
```

**Comment by pjljvandelaar** [comment] 2018-06-28 18:06
I assume we can close this issue

**Comment by dnadales** [comment] 2018-06-28 18:07
Yes, indeed.

**Closed as completed** 2018-06-28 19:29 UTC
Labels: question, torxakis-language, component-txs-compiler
