### ISSUE TITLE
scoping in action prefix

### ISSUE THREAD

**Issue by tretmans** [TorXakis/TorXakis#788] opened 2018-09-10 12:42 UTC
New Compiler;
Model:
```
  1 
  2 CHANDEF  MyChans
  3  ::=
  4     A,B :: Int
  5 ENDDEF
  6 
  7 MODELDEF Mod
  8  ::=
  9     CHAN IN
 10     CHAN OUT A,B
 11 
 12     SYNC {A},{B},{A|B}
 13 
 14     BEHAVIOUR
 15        { A ?x | B ?x } [[ x == 43 ]]  >->  B !x  >->  STOP
 16 ENDDEF
 17 
```
gives
```
TXS >> stepper Mod
TXS >>  Stepper started
TXS >> step 5
TXS >>  .....1: Act { { ( A, [ 72 ] ) ( B, [ 43 ] ) } }
TXS >>  .....2: Act { { ( B, [ 43 ] ) } }
TXS >>  no state or deadlock
TXS >>  FAIL: No Output (Quiescence)
TXS >> 
```
wrong binding of `x` .

**Comment by dnadales** [comment] 2018-12-23 10:16
Might be related to https://github.com/TorXakis/TorXakis/issues/841

**Comment by pjljvandelaar** [comment] 2018-12-24 12:07
IT should be an error: X twice defined in same scope. Exactly as issue #841 states.

**Comment by pjljvandelaar** [comment] 2018-12-24 12:09
Duplicate of #841

**Closed as completed by pjljvandelaar** 2018-12-24 12:09 UTC
Labels: bug, component-txs-compiler
